import type { ChatRealtime } from '@/shared/api/realtime';
import type { MessageJumpRequest } from '@/entities/message';
import type * as React from 'react';
import type { Message, ModalState, ReactionInfo } from '@/entities/message';
import type { GroupRole } from '@/entities/chat';
import type { GroupDetails, GroupParticipant, GroupProfileConfirmState } from './GroupProfileTypes';
import type { Id } from '@/shared/lib/ids';

export type { RawGroupDetails, RawGroupParticipant, RawGroupPendingInvite } from '@/entities/chat';

export interface GroupComponentProps {
  chatId: Id;
  groupName: string;
  username: string;
  firstUnreadMessageId?: Id | null;
  onBack: () => void;
  onOpenUserProfile?: (username: string) => void;
  messageJumpRequest?: MessageJumpRequest | null;
}

export type GroupTranslations = Record<string, string> & { leaveGroupConsequences?: string[]; deleteGroupConsequences?: string[] };

type Setter<T> = React.Dispatch<React.SetStateAction<T>>;
type ContextMenuState = { x: number; y: number; messageId: Id; isMine: boolean; isClosing?: boolean } | null;
type ReactionMenuState = { message: Message; x: number; y: number; isClosing?: boolean } | null;
type ReactionDetailsState = { message: Message; reaction: string; reactions: ReactionInfo[] } | null;

export interface GroupChatViewModel {
  chatId: Id;
  username: string;
  messages: Message[];
  onBack: () => void;
  openGroupProfile: () => void;
  currentGroupAvatar: string;
  currentGroupName: string;
  groupDetails: GroupDetails | null;
  translations: GroupTranslations;
  currentUserId: Id;
  firstUnreadMessageId?: Id | null;
  handleMessageClick: (event: React.MouseEvent, message: Message) => void;
  handleOpenUserProfile: (username: string) => void;
  highlightedMessageId: Id | null;
  contextMenu: ContextMenuState;
  getFormattedDateLabel: (timestamp: string) => string;
  getMessageTime: (timestamp: string) => string;
  canDeleteMessage: (message: Message) => boolean;
  jumpToSearchResult: (messageId: Id) => void;
  setHighlightedMessageId: Setter<Id | null>;
  messageRefs: React.MutableRefObject<Record<Id, HTMLDivElement | null>>;
  scrollToMessage: (messageId: Id) => void;
  chatRealtime: ChatRealtime;
  openMenus: (message: Message, event: React.MouseEvent) => void;
  tempHighlightedMessageId: Id | null;
  setTempHighlightedMessageId: Setter<Id | null>;
  loadOlderMessages: () => Promise<void>;
  hasMoreMessages: boolean;
  isLoadingOlderMessages: boolean;
  isLoadingInitialMessages: boolean;
  loadNewerMessages: () => Promise<void>;
  loadLatestMessages: () => Promise<void>;
  hasMoreNewerMessages: boolean;
  isLoadingNewerMessages: boolean;
  markMessagesRead: (messageIds: Id[]) => Promise<void>;
  isOwnMessage: (message: Message) => boolean;
  setReadStatusMessage: Setter<Message | null>;
  setReactionDetails: Setter<ReactionDetailsState>;
  closeMenus: () => void;
  reactionMenu: ReactionMenuState;
  messageInputRef: React.RefObject<HTMLInputElement | null>;
  messageInput: string;
  setMessageInput: Setter<string>;
  replyTo: Message | null;
  editingMessage: Message | null;
  handleSendMessage: () => void;
  handleFilesUpload: (files: File[], caption?: string) => void;
  cancelUpload: (messageId: Id) => void;
  handleResendMessage: (message: Message) => void;
  setReplyTo: Setter<Message | null>;
  setEditingMessage: Setter<Message | null>;
  token: string;
  handleVoiceMessage: (file: Blob, fileName: string) => void;
  createOptimisticUploadMessage: (file: Blob, fileName: string, fileType?: string, caption?: string) => Id;
  updateOptimisticUploadProgress: (messageId: Id, percent: number) => void;
  markOptimisticUploadFailed: (messageId: Id, errorMessage?: string) => void;
  settleOptimisticUpload: (messageId: Id) => void;
  contextMenuRef: React.RefObject<HTMLDivElement | null>;
  setContextMenu: Setter<ContextMenuState>;
  setModal: Setter<ModalState | null>;
  isClosing: boolean;
  setForwardMessage: Setter<Message | null>;
  reactionMenuRef: React.RefObject<HTMLDivElement | null>;
  setReactionMenu: Setter<ReactionMenuState>;
  renderGroupProfile: boolean;
  isGroupProfileClosing: boolean;
  requestCloseGroupProfile: () => void;
  groupForm: { name: string; description: string };
  setGroupForm: Setter<{ name: string; description: string }>;
  participantInput: string;
  setParticipantInput: Setter<string>;
  isSavingGroup: boolean;
  groupAvatarInputRef: React.RefObject<HTMLInputElement | null>;
  handleGroupAvatarUpload: (event: React.ChangeEvent<HTMLInputElement>) => void | Promise<void>;
  handleSaveGroup: () => void | Promise<void>;
  handleAddParticipant: (usernameOverride?: string) => void | Promise<void>;
  handleRemoveParticipant: (username: string) => void;
  handleRoleChange: (username: string, role: GroupRole) => void | Promise<void>;
  handleTransferOwner: (username: string) => void;
  handleLeaveGroup: () => void;
  handleDeleteGroup: () => void;
  groupConfirm: GroupProfileConfirmState | null;
  setGroupConfirm: Setter<GroupProfileConfirmState | null>;
  unreadParticipants: GroupParticipant[];
  readStatusMessage: Message | null;
  reactionDetails: ReactionDetailsState;
  modal: ModalState | null;
  forwardMessage: Message | null;
}
